{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.121.644.0 (23.09)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Data Professional Survey\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "data_professional_survey.q11__which_country_do_you_live_in_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Data Professional Survey",
                    "ConceptualProperty": "Q11 - Which Country do you live in?.1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Country": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "data_professional_survey.q1__which_title_best_fits_your_current_role_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Data Professional Survey",
                    "ConceptualProperty": "Q1 - Which Title Best Fits your Current Role?.1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Job Title": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "data_professional_survey.q5__favorite_programming_language_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Data Professional Survey",
                    "ConceptualProperty": "Q5 - Favorite Programming Language.1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Favorite Programming Language": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-NG",
    "tables": [
      {
        "name": "Data Professional Survey",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Unique ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c4e1144-d4e2-439a-bcc8-b709dcb61661",
            "sourceColumn": "Unique ID",
            "summarizeBy": "none"
          },
          {
            "name": "Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33ae6e41-5d87-4376-a582-f100dc12a681",
            "sourceColumn": "Email",
            "summarizeBy": "none"
          },
          {
            "name": "Date Taken (America/New_York)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "45b23062-b048-4f65-8465-ce05f9cb4812",
            "sourceColumn": "Date Taken (America/New_York)",
            "summarizeBy": "none"
          },
          {
            "name": "Time Taken (America/New_York)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "d866a2f2-4eab-4e07-98f9-67576230dd5f",
            "sourceColumn": "Time Taken (America/New_York)",
            "summarizeBy": "none"
          },
          {
            "name": "Time Spent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "d97ad892-5307-4d92-b93c-49d20a97f765",
            "sourceColumn": "Time Spent",
            "summarizeBy": "none"
          },
          {
            "name": "Q1 - Which Title Best Fits your Current Role?.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45d40e53-d069-4037-91a8-cccb08c56182",
            "sourceColumn": "Q1 - Which Title Best Fits your Current Role?.1",
            "summarizeBy": "none"
          },
          {
            "name": "Q2 - Did you switch careers into Data?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b770023-750b-4a34-ac95-598f20cca960",
            "sourceColumn": "Q2 - Did you switch careers into Data?",
            "summarizeBy": "none"
          },
          {
            "name": "Average Salary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7b4f2ed7-83dd-46e5-997a-a1d1371c75df",
            "sourceColumn": "Average Salary",
            "summarizeBy": "sum"
          },
          {
            "name": "Q4 - What Industry do you work in?.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "658369ab-28f1-4e27-9744-266278e2fc7a",
            "sourceColumn": "Q4 - What Industry do you work in?.1",
            "summarizeBy": "none"
          },
          {
            "name": "Q5 - Favorite Programming Language.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f8ad4d1-5c01-4e3d-8c00-0fbf500667ec",
            "sourceColumn": "Q5 - Favorite Programming Language.1",
            "summarizeBy": "none"
          },
          {
            "name": "Q6 - How Happy are you in your Current Position with the following? (Salary)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddcfd4c5-00ba-48ad-92ec-f013d69b2c7a",
            "sourceColumn": "Q6 - How Happy are you in your Current Position with the following? (Salary)",
            "summarizeBy": "none"
          },
          {
            "name": "Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "744ccc3b-b208-4155-b0eb-b5570d53f3a8",
            "sourceColumn": "Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)",
            "summarizeBy": "sum"
          },
          {
            "name": "Q6 - How Happy are you in your Current Position with the following? (Coworkers)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08d53ad5-a8a2-49ba-bc56-994e4c75a9bb",
            "sourceColumn": "Q6 - How Happy are you in your Current Position with the following? (Coworkers)",
            "summarizeBy": "none"
          },
          {
            "name": "Q6 - How Happy are you in your Current Position with the following? (Management)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4c59d0a-8d58-4de4-bc63-4caa5b13e3c2",
            "sourceColumn": "Q6 - How Happy are you in your Current Position with the following? (Management)",
            "summarizeBy": "none"
          },
          {
            "name": "Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcda2418-be14-43cd-9bc8-d0848a8077f9",
            "sourceColumn": "Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)",
            "summarizeBy": "none"
          },
          {
            "name": "Q6 - How Happy are you in your Current Position with the following? (Learning New Things)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6c6a973-aa21-4805-9011-55f9bfacd962",
            "sourceColumn": "Q6 - How Happy are you in your Current Position with the following? (Learning New Things)",
            "summarizeBy": "none"
          },
          {
            "name": "Q7 - How difficult was it for you to break into Data?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7df7b85f-6b0d-480d-b6a0-e9d06ff67bc9",
            "sourceColumn": "Q7 - How difficult was it for you to break into Data?",
            "summarizeBy": "none"
          },
          {
            "name": "Q8 - If you were to look for a new job today, what would be the most important t",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16736b5e-d17c-4ce4-81b4-c36561391fc3",
            "sourceColumn": "Q8 - If you were to look for a new job today, what would be the most important t",
            "summarizeBy": "none"
          },
          {
            "name": "Q9 - Male/Female?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1cd5bc13-2900-4384-a1a4-629f2e4b52d8",
            "sourceColumn": "Q9 - Male/Female?",
            "summarizeBy": "none"
          },
          {
            "name": "Q10 - Current Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "658d2233-3600-4f44-82a7-8657f74803c6",
            "sourceColumn": "Q10 - Current Age",
            "summarizeBy": "sum"
          },
          {
            "name": "Q11 - Which Country do you live in?.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d40d437-5dd1-4258-a25c-cb1252faa13c",
            "sourceColumn": "Q11 - Which Country do you live in?.1",
            "summarizeBy": "none"
          },
          {
            "name": "Q12 - Highest Level of Education",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4db7fae-2cbf-4836-9476-5d6ff5f6d2a5",
            "sourceColumn": "Q12 - Highest Level of Education",
            "summarizeBy": "none"
          },
          {
            "name": "Q13 - Ethnicity.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5801fd87-10e1-4808-bd29-e29f5b08c463",
            "sourceColumn": "Q13 - Ethnicity.1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "54ea42c6-5b4c-415b-98c2-20d26a4dd88e",
        "partitions": [
          {
            "name": "Data Professional Survey",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\USER\\Documents\\New folder\\DAMILOLA\\CFI\\BIDA\\Alextheanalyst\\Power BI\\Power BI - Final Project.xlsx\"), null, true),",
                "    #\"Data Professional Survey_Sheet\" = Source{[Item=\"Data Professional Survey\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Data Professional Survey_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Unique ID\", type text}, {\"Email\", type text}, {\"Date Taken (America/New_York)\", type date}, {\"Time Taken (America/New_York)\", type time}, {\"Browser\", type text}, {\"OS\", type text}, {\"City\", type text}, {\"Country\", type text}, {\"Referrer\", type text}, {\"Time Spent\", type time}, {\"Q1 - Which Title Best Fits your Current Role?\", type text}, {\"Q2 - Did you switch careers into Data?\", type text}, {\"Q3 - Current Yearly Salary (in USD)\", type text}, {\"Q4 - What Industry do you work in?\", type text}, {\"Q5 - Favorite Programming Language\", type text}, {\"Q6 - How Happy are you in your Current Position with the following? (Salary)\", Int64.Type}, {\"Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)\", Int64.Type}, {\"Q6 - How Happy are you in your Current Position with the following? (Coworkers)\", Int64.Type}, {\"Q6 - How Happy are you in your Current Position with the following? (Management)\", Int64.Type}, {\"Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)\", Int64.Type}, {\"Q6 - How Happy are you in your Current Position with the following? (Learning New Things)\", Int64.Type}, {\"Q7 - How difficult was it for you to break into Data?\", type text}, {\"Q8 - If you were to look for a new job today, what would be the most important thing to you?\", type text}, {\"Q9 - Male/Female?\", type text}, {\"Q10 - Current Age\", Int64.Type}, {\"Q11 - Which Country do you live in?\", type text}, {\"Q12 - Highest Level of Education\", type text}, {\"Q13 - Ethnicity\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Browser\", \"OS\", \"City\", \"Country\", \"Referrer\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each true),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Filtered Rows\", \"Q1 - Which Title Best Fits your Current Role?\", Splitter.SplitTextByEachDelimiter({\"(\"}, QuoteStyle.Csv, false), {\"Q1 - Which Title Best Fits your Current Role?.1\", \"Q1 - Which Title Best Fits your Current Role?.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"Q1 - Which Title Best Fits your Current Role?.1\", type text}, {\"Q1 - Which Title Best Fits your Current Role?.2\", type text}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type1\",{\"Q1 - Which Title Best Fits your Current Role?.2\"}),",
                "    #\"Split Column by Delimiter1\" = Table.SplitColumn(#\"Removed Columns1\", \"Q4 - What Industry do you work in?\", Splitter.SplitTextByEachDelimiter({\"(\"}, QuoteStyle.Csv, false), {\"Q4 - What Industry do you work in?.1\", \"Q4 - What Industry do you work in?.2\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Split Column by Delimiter1\",{{\"Q4 - What Industry do you work in?.1\", type text}, {\"Q4 - What Industry do you work in?.2\", type text}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Changed Type2\",{\"Q4 - What Industry do you work in?.2\"}),",
                "    #\"Split Column by Delimiter2\" = Table.SplitColumn(#\"Removed Columns2\", \"Q5 - Favorite Programming Language\", Splitter.SplitTextByEachDelimiter({\":\"}, QuoteStyle.Csv, false), {\"Q5 - Favorite Programming Language.1\", \"Q5 - Favorite Programming Language.2\"}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Split Column by Delimiter2\",{{\"Q5 - Favorite Programming Language.1\", type text}, {\"Q5 - Favorite Programming Language.2\", type text}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type3\", each true),",
                "    #\"Removed Columns3\" = Table.RemoveColumns(#\"Filtered Rows1\",{\"Q5 - Favorite Programming Language.2\"}),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Removed Columns3\", each true),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows2\",\"k\",\"000\",Replacer.ReplaceText,{\"Q3 - Current Yearly Salary (in USD)\"}),",
                "    #\"Split Column by Delimiter3\" = Table.SplitColumn(#\"Replaced Value\", \"Q3 - Current Yearly Salary (in USD)\", Splitter.SplitTextByEachDelimiter({\"-\"}, QuoteStyle.Csv, false), {\"Q3 - Current Yearly Salary (in USD).1\", \"Q3 - Current Yearly Salary (in USD).2\"}),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Split Column by Delimiter3\",{{\"Q3 - Current Yearly Salary (in USD).1\", Int64.Type}, {\"Q3 - Current Yearly Salary (in USD).2\", Int64.Type}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type4\",{{\"Q3 - Current Yearly Salary (in USD).2\", Order.Ascending}}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Sorted Rows\",null,225000,Replacer.ReplaceValue,{\"Q3 - Current Yearly Salary (in USD).2\"}),",
                "    #\"Sorted Rows1\" = Table.Sort(#\"Replaced Value1\",{{\"Q3 - Current Yearly Salary (in USD).1\", Order.Ascending}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Sorted Rows1\", \"Average Salary\", each ([#\"Q3 - Current Yearly Salary (in USD).1\"]+[#\"Q3 - Current Yearly Salary (in USD).2\"])/2),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Custom\",{\"Unique ID\", \"Email\", \"Date Taken (America/New_York)\", \"Time Taken (America/New_York)\", \"Time Spent\", \"Q1 - Which Title Best Fits your Current Role?.1\", \"Q2 - Did you switch careers into Data?\", \"Q3 - Current Yearly Salary (in USD).1\", \"Q3 - Current Yearly Salary (in USD).2\", \"Average Salary\", \"Q4 - What Industry do you work in?.1\", \"Q5 - Favorite Programming Language.1\", \"Q6 - How Happy are you in your Current Position with the following? (Salary)\", \"Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)\", \"Q6 - How Happy are you in your Current Position with the following? (Coworkers)\", \"Q6 - How Happy are you in your Current Position with the following? (Management)\", \"Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)\", \"Q6 - How Happy are you in your Current Position with the following? (Learning New Things)\", \"Q7 - How difficult was it for you to break into Data?\", \"Q8 - If you were to look for a new job today, what would be the most important thing to you?\", \"Q9 - Male/Female?\", \"Q10 - Current Age\", \"Q11 - Which Country do you live in?\", \"Q12 - Highest Level of Education\", \"Q13 - Ethnicity\"}),",
                "    #\"Filtered Rows3\" = Table.SelectRows(#\"Reordered Columns\", each true),",
                "    #\"Removed Columns4\" = Table.RemoveColumns(#\"Filtered Rows3\",{\"Q3 - Current Yearly Salary (in USD).1\", \"Q3 - Current Yearly Salary (in USD).2\"}),",
                "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Removed Columns4\",{{\"Average Salary\", Int64.Type}}),",
                "    #\"Split Column by Delimiter4\" = Table.SplitColumn(#\"Changed Type5\", \"Q8 - If you were to look for a new job today, what would be the most important thing to you?\", Splitter.SplitTextByEachDelimiter({\"(\"}, QuoteStyle.Csv, false), {\"Q8 - If you were to look for a new job today, what would be the most important t\", \"Q8 - If you were to look for a new job today, what would be the most important.1\"}),",
                "    #\"Changed Type6\" = Table.TransformColumnTypes(#\"Split Column by Delimiter4\",{{\"Q8 - If you were to look for a new job today, what would be the most important t\", type text}, {\"Q8 - If you were to look for a new job today, what would be the most important.1\", type text}}),",
                "    #\"Removed Columns5\" = Table.RemoveColumns(#\"Changed Type6\",{\"Q8 - If you were to look for a new job today, what would be the most important.1\"}),",
                "    #\"Filtered Rows4\" = Table.SelectRows(#\"Removed Columns5\", each true),",
                "    #\"Split Column by Delimiter5\" = Table.SplitColumn(#\"Filtered Rows4\", \"Q11 - Which Country do you live in?\", Splitter.SplitTextByDelimiter(\"(\", QuoteStyle.Csv), {\"Q11 - Which Country do you live in?.1\", \"Q11 - Which Country do you live in?.2\", \"Q11 - Which Country do you live in?.3\"}),",
                "    #\"Changed Type7\" = Table.TransformColumnTypes(#\"Split Column by Delimiter5\",{{\"Q11 - Which Country do you live in?.1\", type text}, {\"Q11 - Which Country do you live in?.2\", type text}, {\"Q11 - Which Country do you live in?.3\", type text}}),",
                "    #\"Removed Columns6\" = Table.RemoveColumns(#\"Changed Type7\",{\"Q11 - Which Country do you live in?.2\", \"Q11 - Which Country do you live in?.3\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Removed Columns6\",\"\",\"No degree\",Replacer.ReplaceValue,{\"Q12 - Highest Level of Education\"}),",
                "    #\"Split Column by Delimiter6\" = Table.SplitColumn(#\"Replaced Value2\", \"Q13 - Ethnicity\", Splitter.SplitTextByDelimiter(\"(\", QuoteStyle.Csv), {\"Q13 - Ethnicity.1\", \"Q13 - Ethnicity.2\", \"Q13 - Ethnicity.3\"}),",
                "    #\"Changed Type8\" = Table.TransformColumnTypes(#\"Split Column by Delimiter6\",{{\"Q13 - Ethnicity.1\", type text}, {\"Q13 - Ethnicity.2\", type text}, {\"Q13 - Ethnicity.3\", type text}}),",
                "    #\"Removed Columns7\" = Table.RemoveColumns(#\"Changed Type8\",{\"Q13 - Ethnicity.2\", \"Q13 - Ethnicity.3\"}),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Removed Columns7\", {\"Date Taken (America/New_York)\"}),",
                "    #\"Changed Type9\" = Table.TransformColumnTypes(#\"Removed Errors\",{{\"Q6 - How Happy are you in your Current Position with the following? (Salary)\", type text}, {\"Q6 - How Happy are you in your Current Position with the following? (Work/Life Balance)\", Int64.Type}, {\"Q6 - How Happy are you in your Current Position with the following? (Coworkers)\", type text}, {\"Q6 - How Happy are you in your Current Position with the following? (Management)\", type text}, {\"Q6 - How Happy are you in your Current Position with the following? (Upward Mobility)\", type text}, {\"Q6 - How Happy are you in your Current Position with the following? (Learning New Things)\", type text}, {\"Q10 - Current Age\", Int64.Type}})",
                "in",
                "    #\"Changed Type9\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}